# Generated by Django 2.2.6 on 2019-11-11 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoriallac',
            name='contenido_tutorial_lac',
            field=models.TextField(default='contenido'),
        ),
        migrations.AddField(
            model_name='tutoriallac',
            name='fecha_cambio_lac',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 12, 9, 19, 587056), verbose_name='Ultima fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='tutoriallac',
            name='descripcion_tutorial_lac',
            field=models.CharField(max_length=100),
        ),
    ]
